services:
  app:
    container_name: recruitment-task-primeo-app
    build:
      context: .
      dockerfile_inline: |
        FROM php:8.4-cli-alpine
        COPY --from=ghcr.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
        COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
        RUN apk add --no-cache git unzip \
            && install-php-extensions zip bcmath
        WORKDIR /app
        COPY . .
        RUN composer install --no-interaction --no-progress
    command: >
      sh -c "touch database/database.sqlite
      && php artisan migrate:fresh --seed --force
      && php artisan scribe:generate
      && php artisan serve --host=0.0.0.0 --port=8080"
    environment:
      APP_NAME: Employee Management
      APP_ENV: local
      APP_KEY: "base64:Ad2gbAK7fkpRX4HnDF2S5oB+st9nVeKxOoKEWyB6acw="
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
    ports:
      - '8080:8080'
